spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: claimRequest
          uri: http://claimrequest-service:8100
          predicates:
            - Path=/api/claimRequest/**
eureka:
  client:
    register-with-eureka: false
server:
  port: 8222

management:
  tracing:
    sampling:
      probability: 1.0
