eureka:
  client:
    register-with-eureka: false
server:
  port: 8222

spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: claimRequest
          uri: http://localhost:8100
          predicates:
            - Path=/api/claimRequest/**
        - id: policies
          uri: http://localhost:8200
          predicates:
            - Path=/v1/protection-policies/**
        - id: notification
          uri: http://localhost:8300
          predicates:
            - Path=/api/notification/**
  security:
    oauth:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/springboot-microservices-realm
management:
  tracing:
    sampling:
      probability: 1.0